config/routes.rb
Tabsquared::Application.routes.draw do

  root 'welcome#index'

  resources :users, only: [:show, :edit, :update]
  resources :sessions, only: [:create]

  match '/signout', to: 'sessions#destroy', via: :delete

  get '/auth/foursquare/callback', to: 'sessions#create'

  post '/listener', to: 'command#listener'

  post '/test', to: 'command#test'

  post '/verify', to: 'users#verify'

  get '/about', to: 'welcome#about'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :venues

  after_create :find_venues
  
  def self.find_or_create_from_auth_hash(auth_hash)
    uid = auth_hash["uid"]
    where(uid: uid).first_or_initialize.tap do |user|
      user.uid = auth_hash["uid"]
      user.first_name = auth_hash["info"]["first_name"]
      user.last_name = auth_hash["info"]["last_name"]
      user.oauth_token = auth_hash["credentials"]["token"]
      user.save!
    end
  end

  def send_verification_code
    self.update(verification_code: (1000 + rand(8999)).to_s)
    twilio_client = Twilio::REST::Client.new ENV["TWILIO_SID"], ENV["TWILIO_TOKEN"]
    twilio_client.account.sms.messages.create(
      body: "TabSquared Verification Number is #{self.verification_code}",
      to: "+1#{self.phone_number}",
      from: "#{ENV["TWILIO_NUMBER"]}")
  end

  def find_venues
    client = Foursquare2::Client.new(:oauth_token => self.oauth_token)
    client.managed_venues['items'].each do |venue| 
      self.venues << Venue.first_or_create(venue_id: venue.id)
    end
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  helper_method :current_user

  def verify_logged_in
  	redirect_to '/' unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/command_controller.rb
class CommandController < ApplicationController
	skip_before_filter :verify_authenticity_token

	def listener		
    checkin = decode_foursquare_push(request)
		managers = find_managers(checkin)
		checkin[:phone] = managers.select { |manager| manager.notifications && manager.verified }.map { |manager| manager.phone_number}
    checkin[:TWILIO_SID] = ENV["TWILIO_SID"]
    checkin[:TWILIO_TOKEN] = ENV["TWILIO_TOKEN"]
    checkin[:TWILIO_NUMBER] = ENV["TWILIO_NUMBER"]
    checkin[:FOURSQUARE_CLIENT_ID] = ENV["FOURSQUARE_CLIENT_ID"]
    checkin[:FOURSQUARE_CLIENT_SECRET] = ENV["FOURSQUARE_CLIENT_SECRET"]
    send_to_worker(checkin) if checkin[:phone].any?
		render nothing: true
	end

private

  def send_to_worker(checkin)
    HTTParty.post(ENV["WORKER_WEBHOOK_URL"], body: checkin.to_json, options: { :headers => { 'ContentType' => 'application/json' } })
  end

  def find_managers(checkin)
    Venue.find_by(venue_id: checkin['venue']['id']).try(:users)
  end


  def decode_foursquare_push(request)
    JSON.parse(URI.decode_www_form(request.raw_post, enc=Encoding::UTF_8)[0][1])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    
    session[:user_id] = @user.id

    if @user.verified
      redirect_to user_path @user
    else
      redirect_to edit_user_path @user
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :verify_logged_in

  def show
  end

  def edit
  end

  def update
    @user = current_user
    if @user.verified
      @user.update(notifications: params[:user][:notifications])
      flash[:alert] = "update successful"
      render :show
    else
      @user.update(user_params)
      @user.send_verification_code
      render :verify_number
    end
  end

  def verify
    if params[:given_code] == current_user.verification_code
      current_user.update(verified: true)
      redirect_to user_path current_user
    else
      flash[:error] = "Your number did not pass verification..."
      render :verify_number
    end
  end

  private

  def user_params
    params.require(:user).permit(:phone_number, :notifications)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_before_filter :verify_logged_in
	before_filter :check_logged_in
  def index
  end
  def about
  end
  def check_logged_in
  	redirect_to (current_user) if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkin_helper.rb
module CheckinHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tabsquared</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Metrophobic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:800,700' rel='stylesheet' type='text/css'>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
  <%= image_tag 'ajax-loader.gif', id: "spinner" %>

  <footer>
    <strong><center>powered by </center></strong>
    <a href="http://a16z.com/"><%= image_tag("a16z.png", width: '70',) %>
    <a href="http://www.developer.foursquare.com"><%=image_tag("foursquare.png", width: '170',) %></a> 
    <a href="http://www.twilio.com"><%= image_tag("twilio.png", width: '150',) %></a> 
    <a href="http://www.iron.io"><%= image_tag("iron.png", width: '140') %></a>
    <a href="http://www.devbootcamp.com"><%= image_tag("devbootcamp.png", width: '100',) %>
    <a href="http://rubyonrails.org/"><%= image_tag("rails.png", width: '70',) %>
    <a href="https://www.ruby-lang.org/en/"><%= image_tag("ruby.png", width: '70',) %>
    <a href="http://www.heroku.com"><%= image_tag("heroku.png", width: '70',) %>

</footer>
</body>
</html>

app/views/users/edit.html.erb
<!-- <div id="landing-background"> -->
	<div class="jumbotron">
		<p>Please enter the phone number that you wish to receive notifications with.</p>
		<%= form_for current_user do |f| %>
		<%= f.label :phone_number %>:
		<%= f.phone_field :phone_number, placeholder: "123456789 no dashes", pattern: '([0-9]{3}-[0-9]{3}-[0-9]{4})|1*\d{10}', autofocus: "autofocus", required: true, id: "phone-input" %>
		<%= f.submit :class => "btn btn-primary", :value => "Send Me Verification Number" %>
    <br>
    <small>only US area codes supported currently</small>
		<% end %>
	</div>
<!-- </div> -->

app/views/users/show.html.erb
<!-- <div id="landing-background"> -->
	<div class="jumbotron">
    <div class="container">
        <% if current_user %>
      <%= link_to "Sign Out", signout_path, method: :delete, :class => "btn btn-danger pull-right" %>
      <% end %>
      <br>
		<h3>You're all set</h3>
    <span> <%= "#{current_user.first_name.titleize}" %></span>

    <h3>Realtime pushes will be sent to</h3>
    <h2 class="text-primary">
    <%="#{number_to_phone(current_user.phone_number, area_code: true)}"  %>
    </h2>
        <%= form_for current_user do |f| %>
        <%= f.label "notifications" %>
        <%= f.check_box :notifications %>
        <%= f.submit value:"save", :class => "btn btn-success" %>
        <% end  %>

        <% if flash[:alert] %>
        <div class="text-success">
         <strong> <%= flash[:alert]+"!" %></strong>
        </div>
        <% end %>
        </div>
	</div>
<!-- </div> -->

app/views/users/verify_number.html.erb
<!-- <div id="landing-background"> -->
  <div class="jumbotron">
    <% if flash[:error] %>
    <div class="alert alert-danger"><%= flash[:error] %></div>
    <% end %>
    <%= form_tag(verify_path) do %>
    <%= label_tag "Enter verification code" %><br>
    <%= text_field_tag :given_code, "" ,{placeholder: "ex:0000"} %><br>
    <%= submit_tag "Verify", :class => "btn btn-primary", :value => "Submit  Verfication" %>
    <% end %>
  </div>
<!-- </div> -->

app/views/welcome/about.html.erb
  <div class="jumbotron">
  <h1>Team TabSquared</h1>
  <p>Tabsquared was an idea generated at the last minute from the <a href="http://a16zhack2013.eventbrite.com/">Andreessen Horowitz</a> Hackathon in 2013</p>
  <p></p>
  <q>Check out HOROWITZ HOUSE OF UNLIMITED TACOS, PIZZAS, AND BAGELS (Menlo Park) on : <a href="http://4sq.com/1bogucW">@foursquare</a></q><br>
<%= image_tag "team.jpg", width: '30%' %>
  <h4><a href="http://www.github.com/jaredsmithse"> Jared Smith </a>|<a href="http://www.github.com/stephenitis"> Stephen Nguyen </a>|<a href="http://www.github.com/samsamskies"> Sam Miyakawa </a></h4>
</div> 

app/views/welcome/index.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Manage a Foursquare Location?</h1>
        <p>Get realtime push notifications for checkins at your venues and react accordingly!</p>


        <% if current_user %>
        <%= link_to "Sign Out", signout_path, method: :delete %>
        <% else %>
        <p> <%= link_to "Connect with Foursquare", "/auth/foursquare", { class: "btn btn-primary btn-lg"} %></p>
        <% end %>

        <small>Your account must have Manager privileges to sign up</small>
        <small>find out how <strong><a href="http://support.foursquare.com/entries/21376233-Claim-Your-Business-On-Foursquare"> here</a></strong></small>
        <br>
        <br>
        <small><a href="about">about</a></small>

    </div>
</div>